# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='creator',
            new_name='challenger',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='submission',
            name='artifacts',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenger'),
            preserve_default=False,
        ),
    ]
