# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20161007_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='summary',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
