# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
